In [3]:
import subprocess
import os

In [2]:
import subprocess
import os

split_files = os.listdir("Fastq/")
def usearch_merge(file_name,sample_name):
    p = subprocess.call(["usearch10.0.240_win32.exe","-fastq_mergepairs",file_name,\
                         "-fastqout",'Merged/'+sample_name+'.fq',"-sample","Sample"+sample_name])
    return p

i = 1
for files in split_files:
    if ('R1' in files) and ('.gz' not in files):
        input_file = 'Fastq/'+files
        output_file = files.split('_')[0]
        print(output_file)
        p = usearch_merge(input_file,output_file)
        if p == 0:
            print("Usearch completed successfuly for -" + input_file)
        else:
            print("Usearch not done for -" + input_file)
        i = i +1

LF82-10
Usearch completed successfuly for -Fastq/LF82-10_S196_L001_R1_001.fastq
LF82-11
Usearch completed successfuly for -Fastq/LF82-11_S197_L001_R1_001.fastq
LF82-12
Usearch completed successfuly for -Fastq/LF82-12_S198_L001_R1_001.fastq
LF82-13
Usearch completed successfuly for -Fastq/LF82-13_S199_L001_R1_001.fastq
LF82-14
Usearch completed successfuly for -Fastq/LF82-14_S200_L001_R1_001.fastq
LF82-15
Usearch completed successfuly for -Fastq/LF82-15_S201_L001_R1_001.fastq
LF82-16
Usearch completed successfuly for -Fastq/LF82-16_S202_L001_R1_001.fastq
LF82-17
Usearch completed successfuly for -Fastq/LF82-17_S203_L001_R1_001.fastq
LF82-18
Usearch completed successfuly for -Fastq/LF82-18_S204_L001_R1_001.fastq
LF82-19
Usearch completed successfuly for -Fastq/LF82-19_S205_L001_R1_001.fastq
LF82-1
Usearch completed successfuly for -Fastq/LF82-1_S187_L001_R1_001.fastq
LF82-20
Usearch completed successfuly for -Fastq/LF82-20_S206_L001_R1_001.fastq
LF82-21
Usearch completed successfuly for -Fastq/LF82-21_S207_L001_R1_001.fastq
LF82-22
Usearch completed successfuly for -Fastq/LF82-22_S208_L001_R1_001.fastq
LF82-23
Usearch completed successfuly for -Fastq/LF82-23_S209_L001_R1_001.fastq
LF82-24
Usearch completed successfuly for -Fastq/LF82-24_S210_L001_R1_001.fastq
LF82-25
Usearch completed successfuly for -Fastq/LF82-25_S211_L001_R1_001.fastq
LF82-26
Usearch completed successfuly for -Fastq/LF82-26_S212_L001_R1_001.fastq
LF82-27
Usearch completed successfuly for -Fastq/LF82-27_S213_L001_R1_001.fastq
LF82-28
Usearch completed successfuly for -Fastq/LF82-28_S214_L001_R1_001.fastq
LF82-29
Usearch completed successfuly for -Fastq/LF82-29_S215_L001_R1_001.fastq
LF82-2
Usearch completed successfuly for -Fastq/LF82-2_S188_L001_R1_001.fastq
LF82-30
Usearch completed successfuly for -Fastq/LF82-30_S216_L001_R1_001.fastq
LF82-31
Usearch completed successfuly for -Fastq/LF82-31_S217_L001_R1_001.fastq
LF82-32
Usearch completed successfuly for -Fastq/LF82-32_S218_L001_R1_001.fastq
LF82-33
Usearch completed successfuly for -Fastq/LF82-33_S219_L001_R1_001.fastq
LF82-34
Usearch completed successfuly for -Fastq/LF82-34_S220_L001_R1_001.fastq
LF82-35
Usearch completed successfuly for -Fastq/LF82-35_S221_L001_R1_001.fastq
LF82-36
Usearch completed successfuly for -Fastq/LF82-36_S222_L001_R1_001.fastq
LF82-37
Usearch completed successfuly for -Fastq/LF82-37_S223_L001_R1_001.fastq
LF82-38
Usearch completed successfuly for -Fastq/LF82-38_S224_L001_R1_001.fastq
LF82-3
Usearch completed successfuly for -Fastq/LF82-3_S189_L001_R1_001.fastq
LF82-4
Usearch completed successfuly for -Fastq/LF82-4_S190_L001_R1_001.fastq
LF82-5
Usearch completed successfuly for -Fastq/LF82-5_S191_L001_R1_001.fastq
LF82-6
Usearch completed successfuly for -Fastq/LF82-6_S192_L001_R1_001.fastq
LF82-7
Usearch completed successfuly for -Fastq/LF82-7_S193_L001_R1_001.fastq
LF82-8
Usearch completed successfuly for -Fastq/LF82-8_S194_L001_R1_001.fastq
LF82-9
Usearch completed successfuly for -Fastq/LF82-9_S195_L001_R1_001.fastq

In [4]:
"""
The following code is to execute the usearch function. 
"""
import subprocess
import os

split_files = os.listdir("Merged/")
#split_files.remove('desktop.ini')
def usearch_function(file_name,output_filename):
    userfields = "query+target+id+alnlen+mism+opens+qlo+qhi+tlo+thi+evalue+bits+qrow+trow+qrowdots+tstrand+qstrand"
    p = subprocess.call(["usearch10.0.240_win32.exe","-usearch_global",file_name,"-db","Template.txt","-id","0.45",\
                        "-strand","both","-userout",output_filename,"-userfields",\
                        userfields,"-maxaccepts","40","-maxhits","1","-mincols","95","-maxrejects","35"])
    return p

print(len(split_files))
#split_files.remove('desktop.ini')
for files in split_files:
    input_file = 'Merged/'+files
    fine_name = files
    output_file = 'Usearch/'+fine_name+'.txt'
    print(output_file)
    p = usearch_function(input_file,output_file)
    if p == 0:
        print("Usearch completed successfuly for -" + input_file)
    else:
       print("Usearch not done for -" + input_file)

38
Usearch/LF82-1.fq.txt
Usearch completed successfuly for -Merged/LF82-1.fq
Usearch/LF82-10.fq.txt
Usearch completed successfuly for -Merged/LF82-10.fq
Usearch/LF82-11.fq.txt
Usearch completed successfuly for -Merged/LF82-11.fq
Usearch/LF82-12.fq.txt
Usearch completed successfuly for -Merged/LF82-12.fq
Usearch/LF82-13.fq.txt
Usearch completed successfuly for -Merged/LF82-13.fq
Usearch/LF82-14.fq.txt
Usearch completed successfuly for -Merged/LF82-14.fq
Usearch/LF82-15.fq.txt
Usearch completed successfuly for -Merged/LF82-15.fq
Usearch/LF82-16.fq.txt
Usearch completed successfuly for -Merged/LF82-16.fq
Usearch/LF82-17.fq.txt
Usearch completed successfuly for -Merged/LF82-17.fq
Usearch/LF82-18.fq.txt
Usearch completed successfuly for -Merged/LF82-18.fq
Usearch/LF82-19.fq.txt
Usearch completed successfuly for -Merged/LF82-19.fq
Usearch/LF82-2.fq.txt
Usearch completed successfuly for -Merged/LF82-2.fq
Usearch/LF82-20.fq.txt
Usearch completed successfuly for -Merged/LF82-20.fq
Usearch/LF82-21.fq.txt
Usearch completed successfuly for -Merged/LF82-21.fq
Usearch/LF82-22.fq.txt
Usearch completed successfuly for -Merged/LF82-22.fq
Usearch/LF82-23.fq.txt
Usearch completed successfuly for -Merged/LF82-23.fq
Usearch/LF82-24.fq.txt
Usearch completed successfuly for -Merged/LF82-24.fq
Usearch/LF82-25.fq.txt
Usearch completed successfuly for -Merged/LF82-25.fq
Usearch/LF82-26.fq.txt
Usearch completed successfuly for -Merged/LF82-26.fq
Usearch/LF82-27.fq.txt
Usearch completed successfuly for -Merged/LF82-27.fq
Usearch/LF82-28.fq.txt
Usearch completed successfuly for -Merged/LF82-28.fq
Usearch/LF82-29.fq.txt
Usearch completed successfuly for -Merged/LF82-29.fq
Usearch/LF82-3.fq.txt
Usearch completed successfuly for -Merged/LF82-3.fq
Usearch/LF82-30.fq.txt
Usearch completed successfuly for -Merged/LF82-30.fq
Usearch/LF82-31.fq.txt
Usearch completed successfuly for -Merged/LF82-31.fq
Usearch/LF82-32.fq.txt
Usearch completed successfuly for -Merged/LF82-32.fq
Usearch/LF82-33.fq.txt
Usearch completed successfuly for -Merged/LF82-33.fq
Usearch/LF82-34.fq.txt
Usearch completed successfuly for -Merged/LF82-34.fq
Usearch/LF82-35.fq.txt
Usearch completed successfuly for -Merged/LF82-35.fq
Usearch/LF82-36.fq.txt
Usearch completed successfuly for -Merged/LF82-36.fq
Usearch/LF82-37.fq.txt
Usearch completed successfuly for -Merged/LF82-37.fq
Usearch/LF82-38.fq.txt
Usearch completed successfuly for -Merged/LF82-38.fq
Usearch/LF82-4.fq.txt
Usearch completed successfuly for -Merged/LF82-4.fq
Usearch/LF82-5.fq.txt
Usearch completed successfuly for -Merged/LF82-5.fq
Usearch/LF82-6.fq.txt
Usearch completed successfuly for -Merged/LF82-6.fq
Usearch/LF82-7.fq.txt
Usearch completed successfuly for -Merged/LF82-7.fq
Usearch/LF82-8.fq.txt
Usearch completed successfuly for -Merged/LF82-8.fq
Usearch/LF82-9.fq.txt
Usearch completed successfuly for -Merged/LF82-9.fq

['desktop',
 'LF82-1',
 'LF82-10',
 'LF82-11',
 'LF82-12',
 'LF82-13',
 'LF82-14',
 'LF82-15',
 'LF82-16',
 'LF82-17',
 'LF82-18',
 'LF82-19',
 'LF82-2',
 'LF82-20',
 'LF82-21',
 'LF82-22',
 'LF82-23',
 'LF82-24',
 'LF82-25',
 'LF82-26',
 'LF82-27',
 'LF82-28',
 'LF82-29',
 'LF82-3',
 'LF82-30',
 'LF82-31',
 'LF82-32',
 'LF82-33',
 'LF82-34',
 'LF82-35',
 'LF82-36',
 'LF82-37',
 'LF82-38',
 'LF82-4',
 'LF82-5',
 'LF82-6',
 'LF82-7',
 'LF82-8',
 'LF82-9']

In [24]:
#Here we take a look if there is a bottleneck created at the inoculum from the glycerol stock
i = 1
for column in list_files:
    print(column)
    df = convertUsearchToValueCounts(column, column)
    if i == 1:
        df_t0 = df.replace(np.nan,0)
    else:
        df_t0 = df_t0.join(df[[column]].replace(np.nan,0),how='outer')
    print(str(column))
    i = i+1
df_t0

LF82-1
LF82-1
LF82-10
LF82-10
LF82-11
LF82-11
LF82-12
LF82-12
LF82-13
LF82-13
LF82-14
LF82-14
LF82-15
LF82-15
LF82-16
LF82-16
LF82-17
LF82-17
LF82-18
LF82-18
LF82-19
LF82-19
LF82-2
LF82-2
LF82-20
LF82-20
LF82-21
LF82-21
LF82-22
LF82-22
LF82-23
LF82-23
LF82-24
LF82-24
LF82-25
LF82-25
LF82-26
LF82-26
LF82-27
LF82-27
LF82-28
LF82-28
LF82-29
LF82-29
LF82-3
LF82-3
LF82-30
LF82-30
LF82-31
LF82-31
LF82-32
LF82-32
LF82-33
LF82-33
LF82-34
LF82-34
LF82-35
LF82-35
LF82-36
LF82-36
LF82-37
LF82-37
LF82-38
LF82-38
LF82-4
LF82-4
LF82-5
LF82-5
LF82-6
LF82-6
LF82-7
LF82-7
LF82-8
LF82-8
LF82-9
LF82-9

,LF82-1,LF82-10,LF82-11,LF82-12,LF82-13,LF82-14,LF82-15,LF82-16,LF82-17,LF82-18,...,LF82-35,LF82-36,LF82-37,LF82-38,LF82-4,LF82-5,LF82-6,LF82-7,LF82-8,LF82-9
BcsG_H295Y,924,25.0,31.0,71.0,1917,77.0,30,57.0,1580,72.0,...,356,486,78,1704,1342,3328,3035,2291,1853,1159
BcsG_W80R,934,23.0,28.0,123.0,3839,66.0,55,101.0,3040,120.0,...,452,329,125,1773,735,3724,3155,2364,2659,2301
Crp_A145V,886,NaN,3.0,6.0,443,2.0,3,3.0,388,1.0,...,1835,2360,166,839,1681,3783,3412,2640,4863,251
FimH_V77D,1164,63.0,210.0,492.0,1990,21873.0,24720,25965.0,14340,63.0,...,46,14,46,1762,1633,3049,3000,2162,1591,1235
FimH_W124R,934,22359.0,20094.0,38228.0,12456,27.0,17,177.0,1842,54.0,...,50,19,42,2239,660,3968,3509,2560,2181,1292
FimH_delta36,947,790.0,2276.0,4323.0,2088,21.0,19,38.0,1763,38798.0,...,52,18,40,1975,757,3954,3477,2556,1787,1285
WT_1,997,7.0,8.0,28.0,2239,13.0,10,13.0,1746,32.0,...,32,35,41,2008,935,3084,3001,2155,2427,1335
WT_2,834,10.0,21.0,43.0,3442,16.0,23,33.0,2909,20.0,...,26,9,17,1558,658,2600,2426,1759,2110,2130
WT_3,1155,11.0,6.0,22.0,2291,14.0,6,12.0,1777,13.0,...,29,21,33,2167,757,3135,2928,2105,2483,1409
WT_4,483,9.0,14.0,15.0,1360,16.0,14,21.0,1218,11.0,...,57,28,40,1805,292,1493,1298,933,1037,854
WT_Exp,1063,NaN,NaN,NaN,2,NaN,1,NaN,1,NaN,...,46389,15424,42028,15798,1271,3057,3019,2128,2203,3

In [25]:
df_t0[['LF82-1','LF82-2','LF82-3','LF82-4','LF82-5','LF82-6','LF82-7','LF82-8']]

              LF82-1  LF82-2  LF82-3  LF82-4  LF82-5  LF82-6  LF82-7  LF82-8
BcsG_H295Y       924     801    1172    1342    3328    3035    2291    1853
BcsG_W80R        934     381     812     735    3724    3155    2364    2659
Crp_A145V        886     832    1260    1681    3783    3412    2640    4863
FimH_V77D       1164     970    1253    1633    3049    3000    2162    1591
FimH_W124R       934     461     765     660    3968    3509    2560    2181
FimH_delta36     947     583     572     757    3954    3477    2556    1787
WT_1             997     398     519     935    3084    3001    2155    2427
WT_2             834     439     527     658    2600    2426    1759    2110
WT_3            1155     536     810     757    3135    2928    2105    2483
WT_4             483     270     317     292    1493    1298     933    1037
WT_Exp          1063     770    1556    1271    3057    3019    2128    2203

In [26]:
df_t0[['LF82-9','LF82-10','LF82-11','LF82-12','LF82-13']]

              LF82-9  LF82-10  LF82-11  LF82-12  LF82-13
BcsG_H295Y      1159     25.0     31.0     71.0     1917
BcsG_W80R       2301     23.0     28.0    123.0     3839
Crp_A145V        251      NaN      3.0      6.0      443
FimH_V77D       1235     63.0    210.0    492.0     1990
FimH_W124R      1292  22359.0  20094.0  38228.0    12456
FimH_delta36    1285    790.0   2276.0   4323.0     2088
WT_1            1335      7.0      8.0     28.0     2239
WT_2            2130     10.0     21.0     43.0     3442
WT_3            1409     11.0      6.0     22.0     2291
WT_4             854      9.0     14.0     15.0     1360
WT_Exp             3      NaN      NaN      NaN        2

In [27]:
df_t0[['LF82-9','LF82-14','LF82-15','LF82-16','LF82-17']]

              LF82-9  LF82-14  LF82-15  LF82-16  LF82-17
BcsG_H295Y      1159     77.0       30     57.0     1580
BcsG_W80R       2301     66.0       55    101.0     3040
Crp_A145V        251      2.0        3      3.0      388
FimH_V77D       1235  21873.0    24720  25965.0    14340
FimH_W124R      1292     27.0       17    177.0     1842
FimH_delta36    1285     21.0       19     38.0     1763
WT_1            1335     13.0       10     13.0     1746
WT_2            2130     16.0       23     33.0     2909
WT_3            1409     14.0        6     12.0     1777
WT_4             854     16.0       14     21.0     1218
WT_Exp             3      NaN        1      NaN        1

In [28]:
df_t0[['LF82-9','LF82-18','LF82-19','LF82-20','LF82-21']]

              LF82-9  LF82-18  LF82-19   LF82-20  LF82-21
BcsG_H295Y      1159     72.0     41.0      77.0     1902
BcsG_W80R       2301    120.0     39.0     108.0     3605
Crp_A145V        251      1.0      NaN       NaN      461
FimH_V77D       1235     63.0     49.0     112.0     2103
FimH_W124R      1292     54.0     16.0      42.0     1954
FimH_delta36    1285  38798.0  28285.0  100010.0    17194
WT_1            1335     32.0      4.0      36.0     2119
WT_2            2130     20.0     10.0      38.0     3225
WT_3            1409     13.0     10.0      27.0     2235
WT_4             854     11.0     13.0      27.0     1381
WT_Exp             3      NaN      NaN       1.0        6